#!/usr/bin/env python3
"""Build the daily AI Enablement Radar from declared first-party feeds."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlparse
from zoneinfo import ZoneInfo

import feedparser

ROOT = Path(__file__).resolve().parents[1]
IST = ZoneInfo("Asia/Kolkata")

KEYWORDS = {
    "AI platforms": ["ai", "artificial intelligence", "model", "agent", "copilot", "gpt", "gemini"],
    "Workflow": ["workflow", "automation", "productivity", "integration", "workspace"],
    "Governance": ["security", "privacy", "governance", "responsible", "compliance", "admin"],
    "Learning": ["learning", "training", "skill", "education", "course"],
    "CRM": ["sales", "seller", "customer", "crm", "service", "marketing"],
}

RESPONSE = {
    "Governance": "Brief administrators and update guardrails before broad adoption.",
    "Learning": "Convert the change into a short practice activity and manager reinforcement prompt.",
    "CRM": "Map the change to seller or customer workflows and test it with a pilot group.",
    "Workflow": "Demonstrate the changed workflow, define success measures, and support first use.",
    "AI platforms": "Create an awareness brief, role-based examples, and a controlled hands-on trial.",
}

def clean(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value or "")
    return re.sub(r"\s+", " ", html.unescape(text)).strip()

def classify(text: str) -> tuple[str, int]:
    lowered = text.lower()
    scores = {category: sum(1 for term in terms if term in lowered) for category, terms in KEYWORDS.items()}
    category = max(scores, key=scores.get)
    return category, scores[category]

def audience(text: str) -> str:
    lowered = text.lower()
    if any(word in lowered for word in ["developer", "api", "code", "github"]):
        return "Developers and technical teams"
    if any(word in lowered for word in ["sales", "seller", "crm", "customer"]):
        return "Commercial and customer-facing teams"
    if any(word in lowered for word in ["admin", "security", "governance"]):
        return "Administrators and transformation leaders"
    return "Knowledge workers and people managers"

def published_at(entry) -> datetime:
    parsed = entry.get("published_parsed") or entry.get("updated_parsed")
    if parsed:
        return datetime(*parsed[:6], tzinfo=timezone.utc)
    return datetime.now(timezone.utc)

def stable_id(source_id: str, link: str) -> str:
    return hashlib.sha256(f"{source_id}|{link}".encode()).hexdigest()[:16]

def load_json(path: Path, fallback):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else fallback

def write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

def build_report(day: str, checked_at: str, health: dict, new_signals: list[dict]) -> str:
    ok = sum(1 for item in health.values() if item["status"] == "ok")
    lines = [
        f"# AI Enablement Radar — {day}", "",
        "> Automated monitoring record. Interpretations are generated by transparent rules; follow source links for authoritative details.", "",
        "## Monitoring result", "",
        f"- **Sources checked:** {len(health)}",
        f"- **Sources reachable:** {ok}",
        f"- **New material signals:** {len(new_signals)}",
        f"- **Checked at:** {checked_at}", "",
    ]
    if new_signals:
        lines += ["## New signals", ""]
        for signal in new_signals:
            lines += [
                f"### [{signal['title']}]({signal['url']})", "",
                f"- **Source:** {signal['source']}",
                f"- **Published:** {signal['published_at'][:10]}",
                f"- **Domain:** {signal['domain']}",
                f"- **Audience:** {signal['audience']}",
                f"- **Enablement lens:** {signal['enablement_lens']}",
                f"- **Adoption risk:** {signal['adoption_risk']}",
                f"- **Recommended response:** {signal['recommended_response']}", "",
            ]
    else:
        lines += [
            "## No material change detected", "",
            "The configured first-party sources were checked, but no previously unseen item crossed the published relevance threshold. No announcement has been invented to fill the day.", "",
        ]
    lines += ["## Source health", "", "| Source | Status | Items read |", "|---|---:|---:|"]
    for item in health.values():
        lines.append(f"| {item['name']} | {item['status']} | {item['items_read']} |")
    lines += ["", "---", "Generated by the repository's disclosed daily monitoring workflow.", ""]
    return "\n".join(lines)

def build_digest(title: str, items: list[dict]) -> str:
    lines = [f"# {title}", "", "> Automatically assembled from source-linked radar signals.", ""]
    if not items:
        lines += ["No material signals were detected in this period.", ""]
    for item in items:
        lines += [
            f"## [{item['title']}]({item['url']})", "",
            f"**{item['domain']} · {item['audience']} · {item['adoption_risk']} risk**", "",
            item["recommended_response"], "",
        ]
    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", help="Report date in YYYY-MM-DD; defaults to today in Asia/Kolkata")
    args = parser.parse_args()

    now = datetime.now(IST)
    report_date = datetime.strptime(args.date, "%Y-%m-%d").date() if args.date else now.date()
    day = report_date.isoformat()
    checked_at = now.isoformat(timespec="seconds")
    cutoff = datetime.now(timezone.utc) - timedelta(days=10)

    config = load_json(ROOT / "config/sources.json", {"sources": []})
    signals = load_json(ROOT / "data/signals.json", [])
    existing = {item["id"] for item in signals}
    health, discovered = {}, []

    for source in config["sources"]:
        feed = feedparser.parse(source["url"], request_headers={"User-Agent": "AI-Enablement-Radar/1.0"})
        status = "ok" if (not getattr(feed, "bozo", False) or feed.entries) else "error"
        health[source["id"]] = {
            "name": source["name"], "url": source["url"], "status": status,
            "items_read": len(feed.entries), "checked_at": checked_at,
        }
        for entry in feed.entries[:25]:
            link, title = entry.get("link", "").strip(), clean(entry.get("title", ""))
            summary = clean(entry.get("summary", ""))[:500]
            if not link or not title or urlparse(link).scheme not in {"http", "https"}:
                continue
            pub, signal_id = published_at(entry), stable_id(source["id"], link)
            category, score = classify(f"{title} {summary}")
            if signal_id in existing or pub < cutoff or score < 1:
                continue
            lens = "Governance" if category == "Governance" else ("Skill" if category == "Learning" else "Workflow adoption")
            risk = "high" if category == "Governance" else ("medium" if score >= 2 else "low")
            discovered.append({
                "id": signal_id, "title": title, "url": link, "source": source["name"],
                "source_id": source["id"], "published_at": pub.isoformat(), "detected_on": day,
                "domain": category or source["domain"], "audience": audience(f"{title} {summary}"),
                "enablement_lens": lens, "adoption_risk": risk,
                "recommended_response": RESPONSE[category], "summary": summary,
                "automation": "rule-generated",
            })
            existing.add(signal_id)

    discovered.sort(key=lambda item: item["published_at"], reverse=True)
    new_signals = discovered[:12]
    signals = sorted(signals + new_signals, key=lambda item: item["published_at"], reverse=True)[:1000]

    write_json(ROOT / "data/signals.json", signals)
    write_json(ROOT / "data/source-health.json", {"date": day, "sources": health})
    write_json(ROOT / "docs/data/signals.json", signals)
    write_json(ROOT / "docs/data/source-health.json", {"date": day, "sources": health})

    report_path = ROOT / "daily-signals" / day[:4] / f"{day}.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(build_report(day, checked_at, health, new_signals), encoding="utf-8")

    if report_date.weekday() == 6:
        week_start = report_date - timedelta(days=6)
        items = [s for s in signals if week_start.isoformat() <= s["detected_on"] <= day][:20]
        path = ROOT / "weekly-digests" / f"{day}.md"
        path.write_text(build_digest(f"Weekly Enablement Digest — {week_start} to {day}", items), encoding="utf-8")

    if report_date.day == 1:
        previous_end = report_date - timedelta(days=1)
        month = previous_end.strftime("%Y-%m")
        items = [s for s in signals if s["detected_on"].startswith(month)][:40]
        path = ROOT / "monthly-trends" / f"{month}.md"
        path.write_text(build_digest(f"Monthly AI Enablement Trends — {month}", items), encoding="utf-8")

    print(f"Built {report_path.relative_to(ROOT)} with {len(new_signals)} new signals.")

if __name__ == "__main__":
    main()
